# -*- coding: utf-8 -*-
"""WFO-Monte-GOLD-MACD-Reflex Strategy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tu2djKBAm7j3uu6ckcC-xDfZVLOWhm2X
"""

pip install vectorbt yfinance numpy pandas

"""# **Walk Forward Optimization**"""

import pandas as pd
import numpy as np
import yfinance as yf
import vectorbt as vbt
from itertools import product

# -------------------------
# Download Data
# -------------------------
symbol = "GOLD"
start_date = "1960-01-01"
end_date = "2030-01-01"
interval = "1d"

df = yf.download(symbol, start=start_date, end=end_date,
                 interval=interval, multi_level_index=False)

df.index = pd.to_datetime(df.index)

# -------------------------
# Parameter Grid
# -------------------------

MACD_FAST = [10,12,14]
MACD_SIGNAL = [7,9,11]
MACD_SLOW = [22,26,30]

REFLEX_FAST_PERIOD = [4,5,6]
REFLEX_PERIOD = [12,14,16]
REFLEX_SHIFT = [4,5,6]
REFLEX_SLOW_PERIOD = [11,13,15]

# -------------------------
# Indicator Functions
# -------------------------

def rma(series, period):
    return series.ewm(alpha=1/period, adjust=False).mean()

def calculate_reflex(df, rsi_period, fast_period, slow_period):
    df = df.copy()
    delta = df['Close'].diff()
    delta_rma = rma(delta, rsi_period)

    df['Fast_Reflex'] = rma(delta_rma, fast_period)
    df['Slow_Reflex'] = rma(delta_rma, slow_period)
    return df

def reflex_rising(df, rsi_p, fast_p, slow_p, shift):
    df = calculate_reflex(df, rsi_p, fast_p, slow_p)
    return df['Fast_Reflex'] > df['Fast_Reflex'].shift(shift)

def calculate_macd(df, fast, slow, signal):
    df = df.copy()
    df["EMA_fast"] = df["Close"].ewm(span=fast, adjust=False).mean()
    df["EMA_slow"] = df["Close"].ewm(span=slow, adjust=False).mean()
    df["MACD"] = df["EMA_fast"] - df["EMA_slow"]
    df["Signal"] = df["MACD"].ewm(span=signal, adjust=False).mean()
    df["MACD_prev"] = df["MACD"].shift(1)
    return df

def macd_cross_below_0(df, fast, slow, signal):
    df = calculate_macd(df, fast, slow, signal)
    return (df["MACD_prev"] >= 0) & (df["MACD"] < 0)

# -------------------------
# Walk-Forward Optimization
# -------------------------

def run_walk_forward(df, train_years=4, test_years=1):

    results = []

    max_lookback = max(
        MACD_FAST + MACD_SLOW +
        REFLEX_FAST_PERIOD + REFLEX_PERIOD +
        REFLEX_SHIFT + REFLEX_SLOW_PERIOD
    )
    padding = max_lookback + 10

    start_year = df.index[0].year
    end_year = df.index[-1].year

    for train_start in range(start_year,
                             end_year - train_years - test_years + 2):

        train_end = train_start + train_years - 1
        test_start = train_end + 1
        test_end = test_start + test_years - 1

        train_start_idx = df.index.get_loc(df[df.index.year == train_start].index[0])
        train_end_idx   = df.index.get_loc(df[df.index.year == train_end].index[-1])
        test_start_idx  = df.index.get_loc(df[df.index.year == test_start].index[0])
        test_end_idx    = df.index.get_loc(df[df.index.year == test_end].index[-1])

        train_slice = df.iloc[max(0, train_start_idx - padding):train_end_idx + 1].copy()
        test_slice  = df.iloc[max(0, test_start_idx - padding):test_end_idx + 1].copy()

        train_rel_start = train_start_idx - max(0, train_start_idx - padding)
        train_rel_end   = train_end_idx   - max(0, train_start_idx - padding)
        test_rel_start  = test_start_idx  - max(0, test_start_idx - padding)
        test_rel_end    = test_end_idx    - max(0, test_start_idx - padding)

        best_perf = -np.inf
        best_params = None

        for macd_f, macd_s, macd_sig, \
            r_fast, r_period, r_shift, r_slow in product(
                MACD_FAST,
                MACD_SLOW,
                MACD_SIGNAL,
                REFLEX_FAST_PERIOD,
                REFLEX_PERIOD,
                REFLEX_SHIFT,
                REFLEX_SLOW_PERIOD
        ):

            entry_raw = reflex_rising(
                train_slice, r_period, r_fast, r_slow, r_shift
            )

            exit_raw = macd_cross_below_0(
                train_slice, macd_f, macd_s, macd_sig
            )

            entry = entry_raw.iloc[train_rel_start:train_rel_end+1]
            exit = exit_raw.iloc[train_rel_start:train_rel_end+1]

            pf_train = vbt.Portfolio.from_signals(
                close=df['Open'].iloc[train_start_idx:train_end_idx+1],
                entries=entry.shift(1).astype(bool).fillna(False).to_numpy(),
                exits=exit.shift(1).astype(bool).fillna(False).to_numpy(),
                init_cash=100_000,
                fees=0.001,
                slippage=0.002,
                freq='1d'
            )

            if pf_train.total_return() > best_perf:
                best_perf = pf_train.total_return()
                best_params = (
                    macd_f, macd_s, macd_sig,
                    r_fast, r_period, r_shift, r_slow
                )

        results.append({
            "train_period": f"{train_start}-{train_end}",
            "test_period": f"{test_start}-{test_end}",
            "params": best_params,
            "test_slice": test_slice,
            "test_rel_start": test_rel_start,
            "test_rel_end": test_rel_end
        })

    return results

# -------------------------
# Run WFO
# -------------------------

wf_results = run_walk_forward(df)

# -------------------------
# Combine Test Periods
# -------------------------

combined = pd.DataFrame()

print("=== Walk-Forward Optimized Parameters ===")

for i, res in enumerate(wf_results):

    macd_f, macd_s, macd_sig, \
    r_fast, r_period, r_shift, r_slow = res["params"]

    print(
        f"{i+1}: Train {res['train_period']} | Test {res['test_period']} | "
        f"MACD({macd_f},{macd_s},{macd_sig}) | "
        f"REFLEX(fast={r_fast}, period={r_period}, shift={r_shift}, slow={r_slow})"
    )

    test_slice = res["test_slice"]

    test_slice["entry_signal"] = reflex_rising(
        test_slice, r_period, r_fast, r_slow, r_shift
    )

    test_slice["exit_signal"] = macd_cross_below_0(
        test_slice, macd_f, macd_s, macd_sig
    )

    trimmed = test_slice.iloc[
        res["test_rel_start"]:res["test_rel_end"] + 1
    ]

    combined = pd.concat([combined, trimmed])

combined = combined.sort_index()

# -------------------------
# Final Portfolio
# -------------------------

pf = vbt.Portfolio.from_signals(
    close=combined["Open"],
    entries=combined["entry_signal"].shift(1).astype(bool).fillna(False).to_numpy(),
    exits=combined["exit_signal"].shift(1).astype(bool).fillna(False).to_numpy(),
    init_cash=100_000,
    fees=0.001,
    slippage=0.002,
    freq='1d'
)

print("\n=== Combined GOLD WFO Portfolio Stats ===")
print(pf.stats())

pf.plot().show()

"""# **Buy and Hold Comparison**"""

# -------------------------
# Download Data
# -------------------------
symbol = "GOLD"
start_date = "2018-01-01"
end_date = "2030-01-01"
interval = "1d"

df_raw = yf.download(
    symbol,
    start=start_date,
    end=end_date,
    interval=interval,
    multi_level_index=False
)
df_raw.index = pd.to_datetime(df_raw.index)

# Buy and Hold Performance Metrics
df_holding = df_raw['Open']
bh_pf = vbt.Portfolio.from_holding(df_holding, init_cash=100_000 , freq='D')
print(bh_pf.stats())

"""# **Monte Carlo Simulation**"""

import os
import numpy as np
import matplotlib.pyplot as plt

# ===============================
# CONFIG
# ===============================
OUTPUT_DIR = "mc_results"
os.makedirs(OUTPUT_DIR, exist_ok=True)

N_SIM = 1000
BLOCK_SIZE = 5
INIT_CASH = 100

# ===============================
# Portfolio daily returns
# ===============================
returns = pf.returns().dropna().values


# ===============================
# Helpers
# ===============================
def save_show(fig, filename):
    fig.savefig(
        os.path.join(OUTPUT_DIR, filename),
        dpi=300,
        bbox_inches="tight"
    )
    plt.show()


# ===============================
# Block Bootstrap
# ===============================
def block_bootstrap_returns(returns, block_size, n_samples):
    n = len(returns)
    samples = np.zeros((n_samples, n))

    for i in range(n_samples):
        idx = 0
        while idx < n:
            start = np.random.randint(0, n - block_size)
            block = returns[start:start + block_size]
            length = min(block_size, n - idx)
            samples[i, idx:idx + length] = block[:length]
            idx += length

    return samples


bootstrapped_returns = block_bootstrap_returns(
    returns,
    block_size=BLOCK_SIZE,
    n_samples=N_SIM
)

# ===============================
# Equity Curves
# ===============================
equity_curves = INIT_CASH * np.cumprod(1 + bootstrapped_returns, axis=1)

# Total return
total_returns = equity_curves[:, -1] / INIT_CASH - 1


# ===============================
# Max Drawdown
# ===============================
def max_drawdown(equity):
    peak = np.maximum.accumulate(equity)
    dd = equity / peak - 1
    return dd.min()

max_drawdowns = np.array([max_drawdown(eq) for eq in equity_curves])


# ===============================
# Sharpe Ratio
# ===============================
def sharpe_ratio(returns, freq=252):
    mean = np.mean(returns)
    std = np.std(returns)
    if std == 0:
        return 0
    return np.sqrt(freq) * mean / std

sharpes = np.array([
    sharpe_ratio(bootstrapped_returns[i])
    for i in range(N_SIM)
])


# ===============================
# Plot: Equity Curves
# ===============================
fig = plt.figure(figsize=(12, 6))
plt.plot(equity_curves.T, alpha=0.05)
plt.axhline(INIT_CASH, linestyle="--")
plt.title("Block Bootstrap Monte Carlo – 1000 Equity Curves")
plt.xlabel("Time")
plt.ylabel("Equity")

save_show(fig, "block_bootstrap_equity_curves.png")


# ===============================
# Histogram Plot Function
# ===============================
def plot_hist_with_stats(
    data,
    title,
    xlabel,
    color,
    filename,
    low_pct=0,
    high_pct=100,
    bins=50
):
    low, high = np.percentile(data, [low_pct, high_pct])
    filtered = data[(data >= low) & (data <= high)]

    fig = plt.figure(figsize=(10, 5))
    plt.hist(filtered, bins=bins, color=color, alpha=0.7, edgecolor="black")

    plt.axvline(np.median(data), color="black", linestyle="--", label="Median")
    plt.axvline(np.percentile(data, 5), color="gray", linestyle=":", label="5%")
    plt.axvline(np.percentile(data, 95), color="gray", linestyle=":", label="95%")

    plt.title(f"{title} ({low_pct}–{high_pct} pct range)")
    plt.xlabel(xlabel)
    plt.ylabel("Frequency")
    plt.legend()
    plt.grid(alpha=0.3)

    save_show(fig, filename)


# ===============================
# Histograms
# ===============================
plot_hist_with_stats(
    total_returns,
    "Monte Carlo Total Return",
    "Total Return",
    "green",
    "mc_total_return.png",
    low_pct=2,
    high_pct=98
)

plot_hist_with_stats(
    max_drawdowns,
    "Monte Carlo Max Drawdown",
    "Max Drawdown",
    "red",
    "mc_max_drawdown.png"
)

plot_hist_with_stats(
    sharpes,
    "Monte Carlo Sharpe Ratio",
    "Sharpe Ratio",
    "blue",
    "mc_sharpe_ratio.png"
)


# ===============================
# Console Prints (UNCHANGED)
# ===============================
print("Total Return Percentiles:")
print(np.percentile(total_returns, [5, 25, 50, 75, 95]))

print("\nMax Drawdown Percentiles:")
print(np.percentile(max_drawdowns, [5, 25, 50, 75, 95]))


# ===============================
# Summary Stats
# ===============================
tr_pct = np.percentile(total_returns, [5, 25, 50, 75, 95])
dd_pct = np.percentile(max_drawdowns, [5, 25, 50, 75, 95])

tr_95, tr_5 = np.percentile(total_returns, [95, 5])
dd_95, dd_5 = np.percentile(max_drawdowns, [95, 5])

print("\n===== Monte Carlo Summary =====")
print(f"Total Return 95%: {tr_95:.2%}")
print(f"Total Return 5% : {tr_5:.2%}")
print(f"Max DD 95%      : {dd_95:.2%}")
print(f"Max DD 5%       : {dd_5:.2%}")


# ===============================
# SAVE SUMMARY TEXT AS PNG
# ===============================
def save_text_png(lines, title, filename):
    fig = plt.figure(figsize=(10, 6))
    plt.axis("off")

    text = title + "\n\n" + "\n".join(lines)

    plt.text(
        0.01, 0.99,
        text,
        ha="left",
        va="top",
        fontsize=12,
        family="monospace"
    )

    save_show(fig, filename)


summary_lines = [
    "Total Return Percentiles:",
    f"  5%  : {tr_pct[0]:.2%}",
    f"  25% : {tr_pct[1]:.2%}",
    f"  50% : {tr_pct[2]:.2%}",
    f"  75% : {tr_pct[3]:.2%}",
    f"  95% : {tr_pct[4]:.2%}",
    "",
    "Max Drawdown Percentiles:",
    f"  5%  : {dd_pct[0]:.2%}",
    f"  25% : {dd_pct[1]:.2%}",
    f"  50% : {dd_pct[2]:.2%}",
    f"  75% : {dd_pct[3]:.2%}",
    f"  95% : {dd_pct[4]:.2%}",
    "",
    "===== Monte Carlo Summary =====",
    f"Total Return 95%: {tr_95:.2%}",
    f"Total Return 5% : {tr_5:.2%}",
    f"Max DD 95%      : {dd_95:.2%}",
    f"Max DD 5%       : {dd_5:.2%}",
]

save_text_png(
    summary_lines,
    title="Monte Carlo Results Summary",
    filename="mc_summary.png"
)